USE [master]
GO

/****** Object:  Database [19ip110]    Script Date: 15.11.2022 8:06:41 ******/
CREATE DATABASE [19ip110]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'19ip110', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\19ip110.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'19ip110_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\19ip110_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [19ip110].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [19ip110] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [19ip110] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [19ip110] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [19ip110] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [19ip110] SET ARITHABORT OFF 
GO

ALTER DATABASE [19ip110] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [19ip110] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [19ip110] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [19ip110] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [19ip110] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [19ip110] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [19ip110] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [19ip110] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [19ip110] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [19ip110] SET  ENABLE_BROKER 
GO

ALTER DATABASE [19ip110] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [19ip110] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [19ip110] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [19ip110] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [19ip110] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [19ip110] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [19ip110] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [19ip110] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [19ip110] SET  MULTI_USER 
GO

ALTER DATABASE [19ip110] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [19ip110] SET DB_CHAINING OFF 
GO

ALTER DATABASE [19ip110] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [19ip110] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [19ip110] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [19ip110] SET QUERY_STORE = OFF
GO

ALTER DATABASE [19ip110] SET  READ_WRITE 
GO

