//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruzhokIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кружок
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Кружок()
        {
            this.Расписание = new HashSet<Расписание>();
        }
    
        public int id_кружка { get; set; }
        public string Название { get; set; }
        public int id_сотрудника { get; set; }
        public int id_ученика { get; set; }
    
        public virtual Сотрудник1 Сотрудник1 { get; set; }
        public virtual Ученик Ученик { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Расписание> Расписание { get; set; }
    }
}
