//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KruzhokIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int id_расписания { get; set; }
        public int id_сотрудника { get; set; }
        public int id_кружка { get; set; }
        public int День_недели { get; set; }
        public int Кабинет { get; set; }
    
        public virtual Кружок Кружок { get; set; }
        public virtual Сотрудник1 Сотрудник1 { get; set; }
    }
}
